name: 'Bob GitHub Action'
description: 'Setup bob and add it to the PATH''
inputs:
  version:
    description: 'Release version'
    required: true
    default: '0.4.0'
runs:
  using: "composite"
  steps:
    - run: mkdir -p "${HOME}/bin"
      shell: bash
    - run: wget -O "${HOME}/bin/bob" https://github.com/benchkram/bob/releases/download/${{ inputs.version }}/bob_${{ inputs.version }}_linux_amd64
      shell: bash
    - run: chmod +x "${HOME}/bin/bob"
      shell: bash
    - run: echo "${HOME}/bin" >> $GITHUB_PATH
      shell: bash
